export const GET_TOP_NEWS_REQUEST = 'GET_TOP_NEWS_REQUEST';
export const GET_TOP_NEWS_SUCCESS = 'GET_TOP_NEWS_SUCCESS';
export const GET_TOP_NEWS_FAILURE = 'GET_TOP_NEWS_FAILURE';

export const GET_NEWS_BY_QUERY_REQUEST = 'GET_NEWS_BY_QUERY_REQUEST';
export const GET_NEWS_BY_QUERY_SUCCESS = 'GET_NEWS_BY_QUERY_SUCCESS';
export const GET_NEWS_BY_QUERY_FAILURE = 'GET_NEWS_BY_QUERY_FAILURE';

export const ENABLE_DARK_MODE = 'ENABLE_DARK_MODE';
export const UPDATE_APP_LANGUAGE = 'UPDATE_APP_LANGUAGE';
